// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgM_cHr8xM9E_muf3sS5Fpte5TqDAS7VY',
    appId: '1:234556111958:web:170c90a32bc74edf83cff7',
    messagingSenderId: '234556111958',
    projectId: 'ceylondash',
    authDomain: 'ceylondash.firebaseapp.com',
    storageBucket: 'ceylondash.firebasestorage.app',
    measurementId: 'G-B8478WL3ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IHsGJCPfQIjw7m4QZbF_oKUmW9ctKBc',
    appId: '1:234556111958:android:ec8404f6a3b1c50a83cff7',
    messagingSenderId: '234556111958',
    projectId: 'ceylondash',
    storageBucket: 'ceylondash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsG9cx2XARHEvPtUbZZCDIeGVZuSdivg',
    appId: '1:234556111958:ios:5af26a0b3b6d751a83cff7',
    messagingSenderId: '234556111958',
    projectId: 'ceylondash',
    storageBucket: 'ceylondash.firebasestorage.app',
    iosClientId: '234556111958-ohlrg5ljaf61nap40fuco581oj9cnphp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfsG9cx2XARHEvPtUbZZCDIeGVZuSdivg',
    appId: '1:234556111958:ios:5af26a0b3b6d751a83cff7',
    messagingSenderId: '234556111958',
    projectId: 'ceylondash',
    storageBucket: 'ceylondash.firebasestorage.app',
    iosClientId: '234556111958-ohlrg5ljaf61nap40fuco581oj9cnphp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgM_cHr8xM9E_muf3sS5Fpte5TqDAS7VY',
    appId: '1:234556111958:web:a5cf627dab49475183cff7',
    messagingSenderId: '234556111958',
    projectId: 'ceylondash',
    authDomain: 'ceylondash.firebaseapp.com',
    storageBucket: 'ceylondash.firebasestorage.app',
    measurementId: 'G-B97QFXVVFD',
  );
}
